services:
  postgres:
    image: postgres:16-alpine
    container_name: space-postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_NAME}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - app-network
    restart: unless-stopped

  space-api:
    build:
      context: .
      dockerfile: ./space-api/Dockerfile
    image: ghcr.io/rasmus2024/seminar1/space-api:latest
    container_name: space-api
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - SERVER_PORT=8080
      - DB_NAME=${DB_NAME}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    ports:
      - "8080:8080"
    networks:
      - app-network

  space-scheduler:
    build:
      context: .
      dockerfile: ./space-scheduler/Dockerfile
    image: ghcr.io/rasmus2024/seminar1/space-scheduler:latest
    container_name: space-scheduler
    depends_on:
      - space-api
    environment:
      - SERVER_PORT=8081
      - APP_SPACE_CENTER_SERVICE_URL=http://space-api:8080/api
    ports:
      - "8081:8081"
    networks:
      - app-network

volumes:
  postgres_data:
    name: space-postgres-data

networks:
  app-network:
    name: space-network
    driver: bridge