services:
  postgres:
    image: postgres:16-alpine
    container_name: space-postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_NAME}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - app-network
    restart: unless-stopped

  space-api:
    build:
      context: .
      dockerfile: ./space-api/Dockerfile
      args:
        - BUILDKIT_INLINE_CACHE=1
    image: ghcr.io/rasmus2024/seminar13/space-api:latest
    container_name: space-api
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_started
      redis:
        condition: service_healthy
    environment:
      - SERVER_PORT=8080
      - DB_HOST=postgres
      - DB_NAME=${DB_NAME}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - TELEMETRY_SERVICE_PORT=9090
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9093
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
    ports:
      - "8080:8080"
    networks:
      - app-network

  space-scheduler:
    build:
      context: .
      dockerfile: ./space-scheduler/Dockerfile
      args:
        - BUILDKIT_INLINE_CACHE=1
    image: ghcr.io/rasmus2024/seminar13/space-scheduler:latest
    container_name: space-scheduler
    depends_on:
      - space-api
    environment:
      - SERVER_PORT=8081
      - APP_SPACE_CENTER_SERVICE_URL=http://space-api:8080/api
    ports:
      - "8081:8081"
    networks:
      - app-network

  telemetry-service:
    build:
      context: .
      dockerfile: ./telemetry-service/Dockerfile
      args:
        - BUILDKIT_INLINE_CACHE=1
    image: ghcr.io/rasmus2024/seminar13/telemetry-service:latest
    container_name: telemetry-service
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - SERVER_PORT=9091
      - TELEMETRY_SERVICE_HOST=telemetry-service
      - TELEMETRY_SERVICE_PORT=9090
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9093
      - DB_HOST=postgres
      - DB_NAME=${DB_NAME}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    ports:
      - "9091:9091"
      - "9090:9090"
    networks:
      - app-network

  kafka:
    image: apache/kafka:4.2.1
    container_name: kafka
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9093,CONTROLLER://0.0.0.0:9094,EXTERNAL://0.0.0.0:29093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9093,EXTERNAL://localhost:29093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9094
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3

    ports:
      - "9093:9093"
      - "29093:29093"

    volumes:
      - ./data/kafka:/tmp/kraft-combined-logs

    networks:
      - app-network

  kafka-ui:
    image: provectuslabs/kafka-ui:v0.7.2
    container_name: kafka-ui
    ports:
      - "8085:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: LOCAL
      KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS: kafka:9093
    depends_on:
      kafka:
        condition: service_started
    networks:
      - app-network

  redis:
    image: redis:7-alpine
    container_name: space-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - redis_data:/data
    networks:
      - app-network
    restart: unless-stopped

volumes:
  postgres_data:
    name: space-postgres-data
  redis_data:
    name: space-redis-data

networks:
  app-network:
    name: space-network
    driver: bridge
