server:
  port: ${SERVER_PORT:8080}
  error:
    include-stacktrace: never
    include-message: never
    include-binding-errors: never
    include-exception: false
    whitelabel:
      enabled: false

grpc:
  client:
    telemetry-service:
      address: ${TELEMETRY_SERVICE_HOST:telemetry-service}:${TELEMETRY_SERVICE_PORT:9090}
      negotiationType: plaintext

telemetry:
  interval-ms : 5000

spring:
  web:
    resources:
      add-mappings: false  # Отключает автоматический маппинг статических ресурсов
  mvc:
    throw-exception-if-no-handler-found: true   # Пробрасывает исключение для отсутствующих эндпоинтов

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:postgres}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 600000
      max-lifetime: 1800000

  jackson:
    serialization:
      fail-on-empty-beans: false

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true

  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      continue-on-error: false

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:29093}
    properties:
      security.protocol: PLAINTEXT
    admin:
      auto-create-topics: true
    consumer:
      group-id: kpo
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "seminars,java.util,java.lang"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  cache:
    type: redis
    redis:
      time-to-live: 600000
      cache-null-values: false
      cache-as-null-value: false
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    connect-timeout: 2000
    timeout: 2000
    lettuce:
      pool:
        max-active: 10
        max-idle: 5
        min-idle: 1
      shutdown-timeout: 100

management:
  server:
    port: 8082
  endpoints:
    web:
      exposure:
        include: health,metrics,caches
  endpoint:
    cache:
      enabled: true
    metrics:
      tags:
        application: space-api
    health:
      show-details: never
      show-components: never
      probes:
        enabled: true